@startuml
participant 中国
participant 朝鮮
participant 日本
hnote over 中国 : 589年　隋が南北朝を統一
日本 -> 中国:607年 小野妹子ら遣隋使派遣
中国 -> 日本:608年 小野妹子の帰国に隋の使者として裴世清同行
中国 -> 朝鮮:611~613年 高句麗大遠征
hnote over 中国 : 618年　唐、中国統一
日本 -> 中国:630年 最初の遣唐使派遣
中国 -> 日本:遣隋留学生や学問僧ら帰国
朝鮮 -> 朝鮮:643年 百済、新羅へ侵攻
朝鮮 -> 中国:643年 新羅、唐へ救援要請
hnote over 日本 : 643年 蘇我入鹿ら山背大兄王を討滅
中国 -> 朝鮮:644~648年 高句麗へ侵攻
hnote over 日本 : 645年 大化の改新
朝鮮 -> 朝鮮:655年 高句麗、新羅へ侵攻
中国 -> 朝鮮:660年 唐・新羅連合、百済討滅
hnote over 朝鮮:百済復興運動
朝鮮 -> 日本:鬼室福信による援軍要請
日本 --> 朝鮮:661年 斉明天皇、救援のため出兵（急死のため中断）
日本 -> 朝鮮:663年 援軍送るが白村江の戦いで大敗
中国 -> 朝鮮:668年 高句麗討滅
hnote over 朝鮮:新羅が朝鮮統一
日本 -> 朝鮮:668年 遣新羅使、派遣
@enduml
